from PyQt5 import QtCore, QtGui, QtWidgets


class GazepointUI(object):
    def setup_ui(self, gazepoint):
        gazepoint.setObjectName("gazepoint")
        gazepoint.resize(400, 380)
        self.horizontalLayoutWidget = QtWidgets.QWidget(gazepoint)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 341, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.labelHost = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelHost.setObjectName("labelHost")
        self.horizontalLayout.addWidget(self.labelHost)
        self.horizontalLayoutWidget_2= QtWidgets.QWidget(gazepoint)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(39, 60, 341, 73))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineResultName = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineResultName.setText("")
        self.lineResultName.setObjectName("LineResultName")
        self.horizontalLayout_2.addWidget(self.lineResultName)
        spacerItem = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonSet = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.buttonSet.setObjectName("buttonSet")
        self.horizontalLayout_2.addWidget(self.buttonSet)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(gazepoint)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(29, 139, 341, 22))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(6, 8, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.labelFileExists = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.labelFileExists.setObjectName("labelFileExists")
        self.horizontalLayout_3.addWidget(self.labelFileExists)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(gazepoint)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 170, 341, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 6, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buttonAck = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.buttonAck.setObjectName("buttonAck")
        self.horizontalLayout_4.addWidget(self.buttonAck)
        self.imgAck = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.imgAck.setText("")
        self.imgAck.setPixmap(QtGui.QPixmap("icons/x.png"))
        self.imgAck.setAlignment(QtCore.Qt.AlignCenter)
        self.imgAck.setObjectName("imgAck")
        self.horizontalLayout_4.addWidget(self.imgAck)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(gazepoint)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(30, 230, 341, 61))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonFeed = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.buttonFeed.setObjectName("buttonFeed")
        self.horizontalLayout_5.addWidget(self.buttonFeed)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(gazepoint)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(69, 299, 261, 61))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.buttonSave = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.buttonSave.setObjectName("buttonSave")
        self.horizontalLayout_6.addWidget(self.buttonSave)
        self.easterEgg = QtWidgets.QLabel(gazepoint)
        self.easterEgg.setGeometry(QtCore.QRect(570, 170, 161, 16))
        self.easterEgg.setObjectName("easterEgg")
        QtCore.QMetaObject.connectSlotsByName(gazepoint)

        _translate = QtCore.QCoreApplication.translate
        gazepoint.setWindowTitle(_translate("gazepoint", "GazepointAPI"))
        gazepoint.setWindowIcon(QtGui.QIcon("icons/icon.png"))
        self.label.setText(_translate("gazepoint", "IP and port:"))
        self.labelHost.setText(_translate("gazepoint", "TextLabel"))
        self.label_2.setText(_translate("gazepoint", "Result file name: "))
        self.buttonSet.setText(_translate("gazepoint", "Set"))
        self.labelFileExists.setText(_translate("gazepoint", ""))
        self.buttonAck.setText(_translate("gazepoint", "Connect"))
        self.buttonFeed.setText(_translate("gazepoint", "Feed data"))
        self.buttonSave.setText(_translate("gazepoint", "Save and exit"))
        self.easterEgg.setText(_translate("gazepoint", "daniela hamalka was here >:)"))
        self.label.setStyleSheet('font-size: 13pt')
        self.labelHost.setStyleSheet("font-size: 13pt")
